os:
  - windows
  - osx
  - linux
language: java
jdk: oraclejdk14

deploy:
  provider: releases
  api_key: $github
  file_glob: true
  file: "build/jpackage/*"
  skip_cleanup: true
  on:
    tags: true