os:
  - windows
  - osx
  - linux
language: shell

install:
  - if [ $TRAVIS_OS_NAME = windows ]; then powershell Install-WindowsFeature Net-Framework-Core && choco install -y openjdk14 wixtoolset; fi;
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y fakeroot; fi;
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install oracle-jdk@14; fi;

jobs:
  include:
    - stage: Assemble
      script: ./gradlew assemble

deploy:
  provider: releases
  api_key: $github
  file_glob: true
  file: "build/jpackage/*"
  skip_cleanup: true
  on:
    tags: true