name: Build Distributions

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew assemble distZip
      - name: Upload Dist
        uses: actions/upload-artifact@v2
        with:
          name: photo2kml
          path: build/distributions/*
  build-mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download JDK 14 with jpackage
        run: wget -q https://download.java.net/java/GA/jdk14/076bab302c7b4508975440c56f6cc26a/36/GPL/openjdk-14_osx-x64_bin.tar.gz
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Extract JDK 14
        uses: brunoborges/justextract@master
        with:
          file: openjdk-14_osx-x64_bin.tar.gz
      - name: Build with Gradle
        run: ./gradlew assemble -Dbadass.jlink.jpackage.home=${GITHUB_WORKSPACE}/jdk-14.jdk/Contents/Home
      - name: Upload Dist
        uses: actions/upload-artifact@v2
        with:
          name: photo2kml
          path: build/distributions/*
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Upload Dist
        uses: actions/upload-artifact@v2
        with:
          name: photo2kml
          path: build/distributions/*