name: Java Build

on: [push]

jobs:
  build:
    runs-on: [macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Download JDK 14 with jpackage
        run: wget -q https://download.java.net/java/GA/jdk14/076bab302c7b4508975440c56f6cc26a/36/GPL/openjdk-14_osx-x64_bin.tar.gz
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Extract JDK 14
        uses: brunoborges/justextract@master
        with:
          file: openjdk-14_osx-x64_bin.tar.gz
      - name: Build with Gradle
        run: ./gradlew dist jpackage -Dbadass.jlink.jpackage.home=${GITHUB_WORKSPACE}/jdk-14.jdk/Contents/Home
      - name: Upload ZIP
        uses: actions/upload-artifact@v1
        with:
          name: photo2kml
          path: build/distributions/Photo2Kml-mac.zip
      - name: Upload PKG
        uses: actions/upload-artifact@v1
        with:
          name: Photo2KmlInstaller
          path: build/installer/Photo2Kml-1.0.pkg